# Generated by Django 3.2.9 on 2021-12-12 22:28

from django.db import migrations, models
import recepies.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(max_length=50, validators=[recepies.validators.validate_unit_of_measure]),
        ),
    ]
