# Generated by Django 3.2.12 on 2022-02-10 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0003_recipeingredient_quantity_as_float'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngredientImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='recepies/')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepies.recipe')),
            ],
        ),
    ]
