# Generated by Django 3.2.12 on 2022-02-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0004_recipeingredientimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredientimage',
            name='image',
            field=models.ImageField(upload_to='recepies/'),
        ),
    ]
