# Generated by Django 3.2.12 on 2022-02-10 16:06

from django.db import migrations, models
import recepies.models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0005_alter_recipeingredientimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredientimage',
            name='image',
            field=models.ImageField(upload_to=recepies.models.recipe_ingredient_image_upload_handler),
        ),
    ]
